create photo, two buttons, quotes in hero-landing-page
chingu-voyages/v40-geckos-team-18 pull request #80
Opened 2022-09-01 22:28 UTC by tramypham2192

I  created the bike woman photo,  two buttons, and the quote responsive. Please review it.

2022-09-02 23:18 UTC, TiciaD requested changes

2022-09-02 23:18 UTC, TiciaD commented on .gitpod.yml
> +
You'll need to remove this file from the commit, this is a configuration file for your GitPod it doesn't need to be in main codebase

2022-09-02 23:18 UTC, TiciaD commented on src/components/Home/Hero.tsx
> +            <Image src={bikeWoman1} className="h-1 w-1" width={200} height={200} alt="..." />
You'll want to put some descriptive text in the `alt` even if the image is just decorative it's good for accessibility purposes

2022-09-02 23:25 UTC, TiciaD commented on src/components/Home/Hero.tsx
> +    <div className="flex flex-col md:flex-row sm:flex-row">
Can you add `justify-center items-center` to this className so it centers the content on the page? Looks good otherwise

2022-09-03 03:03 UTC, victoriacheng15 commented on src/components/Home/Hero.tsx
> +    <div className="flex flex-col md:flex-row sm:flex-row">
To piggyback on this, you don't really need the 2 flex-row there, so you can remove `sm:flex-row`.

2022-09-03 03:03 UTC, victoriacheng15 commented on src/pages/index.tsx
>        </nav>
We have nav component now. This was used as a placeholder and not needed anymore now. 

So please remove the code below.
```html
      <nav className="flex justify-center gap-4">
        <Link href='/electricity'>Electricity</Link>
        <Link href='/fuel'>Fuel</Link>
        <Link href='/travel'>Travel</Link>
        <Link passHref href='/auth/login'>Log in</Link>
        <Link href='/register'>Register</Link>

      </nav>
```

Thank you!

2022-09-05 21:12 UTC, TiciaD approved these changes
@tramypham2192 Looks like you were pushing your changes to your fork of the repo, not this repo so that's why the PR didn't update. I went ahead and added the updates you had from that commit here so we could get the PR approved soon. Thanks for making those changes!

2022-09-05 21:48 UTC, ialej001 approved these changes
Good to go pending merge conflict update.

2022-09-05 21:50 UTC, merged